channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor
  - goosefem
  - gmatelastoplasticqpot

  # optional dependencies
  - xsimd

  # build tools
  - cmake
  - setuptools_scm

  # Python API
  - python
  - pyxtensor

  # run tests
  - catch2
  - fmt
  - python-goosefem
  - python-gmattensor
  - python-gmatelastoplasticqpot
  - numpy

  # run examples
  - fmt
  - highfive
  - h5py
  - matplotlib

  # generate docs
  - doxygen
